LTST syntax fix
Silently breaks ZCAM scene scanning in ROIStudio (which uses Python 3.11), see traceback.  Added double quotes around LTST to match existing formatting convention.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "asdf\zcam_bandset.py", line 35, in <module>
    from asdf.format import (
  File "asdf\format.py", line 33, in <module>
    from pretty_plot.pplot_utils import obsgeom_string
  File "pretty_plot\pplot_utils.py", line 249
    annotation += f' ltst {line['LTST']}'
                                 ^^^^
SyntaxError: f-string: unmatched '['